# Generated by Django 3.0.3 on 2020-02-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_handling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_name',
            name='model_file',
            field=models.FileField(upload_to='modelFiles'),
        ),
        migrations.AlterField(
            model_name='app_name',
            name='toml_file',
            field=models.FileField(upload_to='TOML_Files'),
        ),
    ]
